### ISSUE TITLE
Please add cl-ruby

### ISSUE THREAD

**Issue by Ninjacop** [quicklisp/quicklisp-projects#1650] opened 2019-02-21 00:07 UTC
> Updated and tested 

This is an FFI between Ruby and Common Lisp, where Ruby scripts can be used in CL, and Ruby 
variables, constants and functions can be declared and called in CL.

Documentation - [https://github.com/Ninjacop/cl-ruby/tree/master/doc](https://github.com/Ninjacop/cl-ruby/tree/master/doc)
Repository - [https://github.com/Ninjacop/cl-ruby](https://github.com/Ninjacop/cl-ruby)

**Comment by phoe** [comment] 2019-02-21 07:04
Duplicate of https://github.com/quicklisp/quicklisp-projects/issues/1631

**Closed** 2019-05-29 16:12 UTC
Labels: canbuild
